name: CI

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-10.15
          - ubuntu-18.04
        include:
          - { os: macos-10.15 , toolchain: stable-x86_64-apple-darwin      }
          - { os: ubuntu-18.04, toolchain: stable-x86_64-unknown-linux-gnu }

    name: ${{ matrix.os }} (${{ matrix.toolchain }})
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup `${{ matrix.toolchain }}`
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          default: true
          profile: default

      - name: '`cargo run --manifest-path ./with-curl-sys-0-4-27-http2-enabled/Cargo.toml -v`'
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --manifest-path ./with-curl-sys-0-4-27-http2-enabled/Cargo.toml -v

      - name: '`cargo run --manifest-path ./with-curl-sys-0-4-28-http2-enabled/Cargo.toml -v`'
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --manifest-path ./with-curl-sys-0-4-28-http2-enabled/Cargo.toml -v

